/**
 * Appointment Decision System API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs/Observable';


import { SurveyNotification } from '../model/surveyNotification';
import { SurveyNotificationListResponse } from '../model/surveyNotificationListResponse';


import { Configuration }                                     from '../configuration';


export interface SurveyNotificationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Get all survey notifications for current user and apply filters
    * 
    * @param read Whether to get read or unread survey notifications. If not specified, all survey notifications are returned.
    */
    getSurveyNotifications(read?: boolean, extraHttpRequestParams?: any): Observable<SurveyNotificationListResponse>;

    /**
    * Marks a survey notification as read
    * 
    * @param surveyNotificationId 
    */
    readSurveyNotification(surveyNotificationId: number, extraHttpRequestParams?: any): Observable<SurveyNotification>;

}
